### ISSUE TITLE
Clicking a submit button on it's top edge does not submit

### ISSUE THREAD

**Issue by rlewan** [alphagov/govuk_elements#545]
Clicking an `input type="submit"` button stylised with the `button` CSS class on it's top edge displays a click animation, but does not submit the form.

#### How would you expect it to work?

The form should be submitted as normal.

#### How does it work currently?

The animation is displayed and element catches focus, but the click does not actually happen. Form is not submitted.

#### Explain the steps to reproduce the bug
1. Go to any form with `input type="submit" class="button"`,
2. Click the button in it's top edge -- slide the mouse pointer down from above the button, click just as the pointer graphic changes from arrow to the pointing finger.

#### Tell us about your environment
* Version used: 3.0.2
* Browser Name and version: Google Chrome 60.0.3112.90
* Operating System and version (desktop or mobile): macOS Sierra 10.12.6

**Comment by andymantell** [comment]
After initial investigation on the x-gov slack channel it looks like it's caused by the `top: 2px` that gets applied to the button when it is `:active`. So what is happening is that as soon as you mousedown, the button moves out the way and you are no longer on top of the button. I can't find the page I was reading, but it seems that the browser defines a click as a mousedown and a mouseup on the element. Because the button slinks out the way, you only get the mousedown half, and therefore no click.

Couple of options as I see it:

1) Find another way of achieving this movement without moving the hit area of the button
2) Change the design so that the button doesn't move like this

**Comment by fofr** [comment]
![button-problem](https://user-images.githubusercontent.com/319055/29170262-98fb342e-7dcf-11e7-8d05-4ce4413194ee.gif)

**Comment by quis** [comment]
Using `transform: translate(0, 2px);` instead of `top: 2px` seems to have the same problem.

**Comment by fofr** [comment]
Doesn't seem to be a problem here:
https://www.gov.uk/apply-renew-passport

**Comment by adamliptrot-oc** [comment]
Looks like the example in @fofr comment uses a pseudo element to maintain the click area

**Comment by igloosi** [comment]
there seems to be a communal x-gov effort. When someone has a feasible solution, can they submit a PR please?

**Comment by quis** [comment]
Here’s the relevant CSS being used in the GOV.UK links @fofr posted:
```css
.button {
   position: relative;
}

.button:before {
    content: "";
    height: 110%;
    width: 100%;
    display: block;
    background: transparent;
    position: absolute;
    top: 0;
    left: 0;
}

.button:active:before {
    top: -10%;
    height: 120%;
}
```
